### ISSUE TITLE
FireEnjin Components

### ISSUE THREAD

**Issue by popcorn245** [jdecode-dev/jdecode-app#2]
Hi, I noticed you are using @madnesslabs/fireenjin-components (or at least have it installed) and I just wanted to know what your use case was and if or how it was helpful.  Sorry to contact you this way, just didn't have another way to contact you via your profile.

**Comment by jdecode-dev** [comment]
Hi Bobby, I'm a student trying to learn Stencil and I found your tutorials in YouTube where really useful. So that's why I checked your projects and your code. Actually I'm learning a lot from them. So thank you for inspiration. Have a nice day!

**Comment by popcorn245** [comment]
No problem, happy to help you on your coding journey. Have some big stuff in the works and a return to YouTube so stay tuned! ^_^

And if you ever want to chat feel free to jump on our discord. Happy coding! ^,^🎵

https://discord.gg/Za9GKnAS

**Comment by jdecode-dev** [comment]
Nice to talk to you 😄. That's good news! I really enjoy your videos and I am learning a lot from them. 
Maybe when I will have more knowledge I will join to your discord chat. Happy coding too 👨‍💻
